open:
  vincentf13:
    security:
      jwt:
        secret: change-me-change-me-change-me-change
        issuer: open.vincentf13
        access-token-ttl-seconds: 3600
        refresh-token-ttl-seconds: 604800
        session-store-prefix: open:sessions
        check-session-active: false
