POST http://infra-kafka-connect.default.svc.cluster.local:8083/connectors
Content-Type: application/json

{
  "name": "mysql-cdc",
  "config": {
    "connector.class": "io.debezium.connector.mysql.MySqlConnector",
    "database.hostname": "infra-mysql-0.infra-mysql-headless.default.svc.cluster.local",
    "database.port": "3306",
    "database.user": "root",
    "database.password": "root",
    "database.server.id": "5401",
    "topic.prefix": "infra-mysql-0",
    "database.include.list": "exchange",
    "table.include.list": "exchange.mq_outbox",
    "snapshot.mode": "initial",
    "schema.history.internal.kafka.bootstrap.servers": "infra-kafka.default.svc.cluster.local:9092",
    "schema.history.internal.kafka.topic": "cdc.infra-mysql-0",
    "schema.history.internal.kafka.replication.factor": "3",
    "tombstones.on.delete": "false",
    "transforms": "mq_outbox",
    "transforms.mq_outbox.type": "io.debezium.transforms.outbox.EventRouter",
    "transforms.mq_outbox.route.by.field": "aggregate_type",

    "transforms.mq_outbox.route.topic.replacement": "${routedByValue}",
    "transforms.mq_outbox.table.field.event.id": "event_id",
    "transforms.mq_outbox.table.field.event.key": "aggregate_id",
    "transforms.mq_outbox.table.field.event.type": "event_type",
    "transforms.mq_outbox.table.field.payload": "payload",
    "transforms.mq_outbox.table.fields.additional.placement": "headers:header:all",
    "poll.interval.ms": "50",
    "producer.override.linger.ms": "0"
  }
}

###

PUT http://infra-kafka-connect.default.svc.cluster.local:8083/connectors/mysql-cdc/config
Content-Type: application/json

{
  "connector.class": "io.debezium.connector.mysql.MySqlConnector",
  "database.hostname": "infra-mysql-0.infra-mysql-headless.default.svc.cluster.local",
  "database.port": "3306",
  "database.user": "root",
  "database.password": "root",
  "database.server.id": "5401",
  "topic.prefix": "infra-mysql-0",
  "database.include.list": "exchange",
  "table.include.list": "exchange.mq_outbox",
  "snapshot.mode": "initial",
  "schema.history.internal.kafka.bootstrap.servers": "infra-kafka.default.svc.cluster.local:9092",
  "schema.history.internal.kafka.topic": "cdc.infra-mysql-0",
  "schema.history.internal.kafka.replication.factor": "3",
  "tombstones.on.delete": "false",
  "transforms": "mq_outbox",
  "transforms.mq_outbox.type": "io.debezium.transforms.outbox.EventRouter",
  "transforms.mq_outbox.route.by.field": "aggregate_type",

  "transforms.mq_outbox.route.topic.replacement": "${routedByValue}",
  "transforms.mq_outbox.table.field.event.id": "event_id",
  "transforms.mq_outbox.table.field.event.key": "aggregate_id",
      "transforms.mq_outbox.table.field.event.type": "event_type",
      "transforms.mq_outbox.table.field.payload": "payload",
      "transforms.mq_outbox.table.fields.additional.placement": "headers:header:all",
          "poll.interval.ms": "50",
          "producer.override.linger.ms": "0"
        }
###

GET http://infra-kafka-connect.default.svc.cluster.local:8083/connectors
Content-Type: application/json


###

GET http://infra-kafka-connect.default.svc.cluster.local:8083/connectors/mysql-cdc/status
Content-Type: application/json



###

DELETE http://infra-kafka-connect.default.svc.cluster.local:8083/connectors/mysql-cdc