@port = 5047

### 重置 Kafka Offset 範例
POST http://localhost:{{port}}/infra/kafka/seek
Content-Type: application/json

{
  "topic": "positions.open-to-close-compensation",
  "partition": 0,
  "offset": null
}


### 切換 log 等級
POST http://localhost:{{port}}/api/logging
Content-Type: application/json

{
  "kafka": false,
  "mvc": false,
  "feign": true,
  "mybatis": false
}
