@namespace = exchange
@gatewayHost = http://localhost:12345
@userEmail = user-{{$uuid}}@example.com
@userPassword = P@ssw0rd!
@externalId = demo-user{{$uuid}}

###
# @name registerUser
POST {{gatewayHost}}/user/api/user
Content-Type: application/json
Accept: application/json

{
  "email": "{{userEmail}}",
  "password": "{{userPassword}}",
  "externalId": "{{externalId}}"
}

> {%
    const email = response.body?.data?.email ?? request.variables.get("userEmail");

    client.test("registerUser: HTTP 200", () => client.assert(response.status === 200));
    client.test("registerUser: OpenApi success", () => client.assert(response.body?.code === "0", "Unexpected response code: " + response.body?.code));
    client.global.set("registeredUserId", response.body?.data?.id);
    client.global.set("registeredUserEmail",email);
%}

###
# @name login
POST {{gatewayHost}}/auth/api/login
Content-Type: application/json
Accept: application/json

{
  "email": "{{registeredUserEmail}}",
  "password": "{{userPassword}}"
}

> {%
    const accessTokenTmp = response.body?.data?.jwtToken;
    const refreshTokenTmp = response.body?.data?.refreshToken;

    client.log("Response body: " + JSON.stringify(response.body));
    client.log("accessTokenTmp: " + accessTokenTmp);
    client.log("refreshTokenTmp: " + refreshTokenTmp);

    client.test("login: HTTP 200", () => client.assert(response.status === 200));
    client.test("login: token issued", () => {
        client.assert(response.body?.code === "0", "Unexpected response code: " + response.body?.code);
        client.assert(accessTokenTmp, "accessToken missing in response body");
        client.assert(refreshTokenTmp, "refreshToken missing in response body");
    });
    client.global.set("accessToken", accessTokenTmp);
    client.global.set("refreshToken", refreshTokenTmp);

    client.log("Set accessToken to global: " + client.global.get("accessToken"));
    client.log("Set refreshToken to global: " + client.global.get("refreshToken"));
%}

###
# @name getUserMe
GET {{gatewayHost}}/user/api/user/me
Authorization: Bearer {{accessToken}}
Accept: application/json

> {%
client.test("getUserMe: HTTP 200", () => client.assert(response.status === 200));
client.test("getUserMe: user data returned", () => {
    client.assert(response.body?.code === "0", "Unexpected response code: " + response.body?.code);
    client.assert(response.body?.data?.id, "User ID missing in response");
    client.assert(response.body?.data?.email === client.global.get("registeredUserEmail"), "Email mismatch");
});
client.log("User Info: " + JSON.stringify(response.body?.data));
%}
