logging:
  level:
    # MyBatis 核心層的預設日誌等級
    org.mybatis: warn
#    org.springframework.transaction: INFO
#    org.springframework.transaction.interceptor: INFO
#    org.mybatis.spring.SqlSessionUtils: INFO

open:
  vincentf13:
    mybatis:
      mapper-sql-logging:
        enabled: false

spring:
  datasource:
    dynamic:
      # 預設資料源群組，未標註 @DS 時會使用這組
      primary: db0_master
      # 找不到指定資料源時是否拋錯；開發期建議 false 方便 fallback
      strict: false
      # 僅在首次使用時才初始化連線池，減少啟動時間
      lazy: true
      # 讀寫分離情境下的負載策略，輪詢傳來的 replicas
      strategy: com.baomidou.dynamic.datasource.strategy.LoadBalanceDynamicDataSourceStrategy
      datasource:
        # === db0 群組 ===
        db0_master:
          url: jdbc:mysql://infra-mysql-0.infra-mysql-headless.default.svc.cluster.local:3306/${MYSQL_DATABASE:exchange}?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC&connectTimeout=3000&socketTimeout=15000&tcpKeepAlive=true&rewriteBatchedStatements=true&allowMultiQueries=true&cachePrepStmts=true&prepStmtCacheSize=256&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&useLocalSessionState=true
          username: ${MYSQL_USERNAME:root}
          password: ${MYSQL_PASSWORD:root}
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            # 連線最大生命週期，需低於 MySQL wait_timeout，避免被伺服器強制關閉
            max-lifetime: 1700000   # ~28 分鐘
            # 閒置多久回收連線，建議為 max-lifetime 的一半左右
            idle-timeout: 600000    # 10 分鐘
            # 池內最大連線數，依服務併發量和 DB 能力調整
            maximum-pool-size: 5
            # 保留的最小閒置連線數，兼顧冷啟動與資源利用
            minimum-idle: 1
            # 等待連線取得的最長毫秒數，超時立即拋 SQLException
            connection-timeout: 30000
            # 驗證連線可用性的逾時，縮短剔除壞連線的時間
            validation-timeout: 5000
        db0_slave:
          url: jdbc:mysql://infra-mysql-0.infra-mysql-headless.default.svc.cluster.local:3306/${MYSQL_DATABASE:exchange}?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC&connectTimeout=3000&socketTimeout=15000&tcpKeepAlive=true&rewriteBatchedStatements=true&allowMultiQueries=true&cachePrepStmts=true&prepStmtCacheSize=256&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&useLocalSessionState=true
          username: ${MYSQL_USERNAME:root}
          password: ${MYSQL_PASSWORD:root}
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            max-lifetime: 1700000
            idle-timeout: 600000
            maximum-pool-size: 4
            minimum-idle: 1
            connection-timeout: 30000
            validation-timeout: 5000
        # === db1 群組 ===
        db1_master:
          url: jdbc:mysql://infra-mysql-1.infra-mysql-headless.default.svc.cluster.local:3306/${MYSQL_DATABASE:exchange}?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC&connectTimeout=3000&socketTimeout=15000&tcpKeepAlive=true&rewriteBatchedStatements=true&allowMultiQueries=true&cachePrepStmts=true&prepStmtCacheSize=256&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&useLocalSessionState=true
          username: ${MYSQL_USERNAME:root}
          password: ${MYSQL_PASSWORD:root}
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            max-lifetime: 1700000
            idle-timeout: 600000
            maximum-pool-size: 5
            minimum-idle: 1
            connection-timeout: 30000
            validation-timeout: 5000
        db1_slave:
          url: jdbc:mysql://infra-mysql-1.infra-mysql-headless.default.svc.cluster.local:3306/${MYSQL_DATABASE:exchange}?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC&connectTimeout=3000&socketTimeout=15000&tcpKeepAlive=true&rewriteBatchedStatements=true&allowMultiQueries=true&cachePrepStmts=true&prepStmtCacheSize=256&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true&cacheResultSetMetadata=true&cacheServerConfiguration=true&useLocalSessionState=true
          username: ${MYSQL_USERNAME:root}
          password: ${MYSQL_PASSWORD:root}
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            max-lifetime: 1700000
            idle-timeout: 600000
            maximum-pool-size: 4
            minimum-idle: 1
            connection-timeout: 30000
            validation-timeout: 5000

mybatis:
  # Mapper XML 放置位置（支援多層目錄）
  mapper-locations: classpath*:mapper/**/*.xml
  # Domain/DTO 套件路徑（依實際專案填寫，可多個路徑以逗號分隔）
  #  type-aliases-package: com.example.app.model
  # TypeHandler 集中配置；若無自訂可省略
  # type-handlers-package: com.example.app.mybatis.handler
  configuration:
    # snake_case 欄位自動轉 camelCase 屬性
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    # 預設關閉二級快取，改採分散式快取時再開
    cache-enabled: false
    # 避免單一慢 SQL 佔用連線的安全停等秒數
    default-statement-timeout: 30
    # 參數為 null 時指定 JDBC 類型，減少 DB 兼容性問題
    jdbc-type-for-null: NULL
    # 將本地快取範圍降到 STATEMENT，減少記憶體占用與髒讀風險
    local-cache-scope: STATEMENT
    # 建議關閉 lazy loading
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
    # REUSE 可重用 PreparedStatement
    default-executor-type: REUSE
    # 使用 Log4j2 ；可統一由框架控制輸出層級與目的地
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    # insert/update 自動回填 auto_increment 主鍵
    use-generated-keys: true
    # 查詢預設 fetchSize，配合驅動減少記憶體占用
    default-fetch-size: 200
    # 對查詢結果 null 欄位也呼叫 setter，避免忽略顯式清空
    call-setters-on-nulls: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      update-strategy: not_null
