management:
  endpoints.web.exposure.include: health,info,metrics,prometheus
  metrics:
    tags:
      app: ${spring.application.name}
      env: ${APP_ENV:dev}
    web:
      server:
        request:
          autotime:
            enabled: true        # 是否自動計時，預設 true
            percentiles: 0.5,0.9,0.95,0.99  # 計算百分位數
            percentiles-histogram: true     # 是否開啟直方圖，適合 Prometheus
        max-uri-tags: 100          # URI 標籤上限，防止維度爆炸