spring:
  kafka:                                                                                           
    bootstrap-servers: infra-kafka.default.svc.cluster.local:9092   # 需自訂
    admin:                                                                                         
      auto-create: true     # 預設 true，偵測到 NewTopic 就建立                                    
      fail-fast: true       # 若 Kafka broker 無法連線則啟動失敗                                   
    producer:                                                                                      
      # 預設使用 byte[] 序列化，統一交由 ObjectMapper 控制 payload 編碼                            
      key-serializer: org.apache.kafka.common.serialization.StringSerializer                       
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer                  
      properties:
        spring.json.add.type.headers: true
        # 傳輸可靠性                                                                               
        acks: all                                                                                  
        enable.idempotence: true                                                                   
        # 壓縮與批次                                                                               
        compression.type: none                                                                     
        linger.ms: 0                                                                              
        batch.size: 32768                                                                         
        buffer.memory: 33554432                                                                    
        # 重試與順序控制                                                                           
        retries: 10                                                                                
        max.in.flight.requests.per.connection: 2                                                   
        # 傳送逾時設定                                                                             
        request.timeout.ms: 30000                                                                  
        delivery.timeout.ms: 120000
    consumer:
      # 減少 rebalance 時的服務中斷。
      partition-assignment-strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor

      # 第一次消費時的起始位置 earliest || latest。
      auto-offset-reset: latest
      enable-auto-commit: false
      # 一次 poll() 調用最多拉取的訊息數量。
      max-poll-records: 20
      # Consumer 健康檢查的最大間隔。下游服務應根據自身最長處理時間來覆蓋此值。
      max-poll-interval-ms: 300000 # 5 分鐘
      # 反序列化
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        group.instance.id: ${spring.application.name}-${random.uuid}
        session.timeout.ms: 10000
        heartbeat.interval.ms: 3000
        fetch.min.bytes: 1
        fetch.max.wait.ms: 10
    listener:
      # 手動 ACK
      ack-mode: manual
      sync-commits: false   # async commit

logging:
  level:
    # Spring Kafka 關鍵 (開發調試時可開啟)
    org.springframework.kafka: INFO
    org.springframework.kafka.core.KafkaTemplate: INFO
    org.springframework.kafka.listener.KafkaMessageListenerContainer: INFO
    org.springframework.kafka.support.serializer: INFO
    # Kafka 原生 (開發調試時可開啟)
    # org.apache.kafka.clients: INFO
    # org.apache.kafka.clients.consumer.internals.AbstractCoordinator: INFO
