apiVersion: v1
kind: Service
metadata:
  name: infra-nacos-headless
  labels:
    app: infra-nacos
    # 為 StatefulSet 提供穩定 DNS。
spec:
  clusterIP: None
  selector:
    app: infra-nacos
  ports:
    - name: http
      port: 8848
      targetPort: 8848
    - name: grpc
      port: 9848
      targetPort: 9848
    - name: grpc-client
      port: 9849
      targetPort: 9849
---
apiVersion: v1
kind: Service
metadata:
  name: infra-nacos
  labels:
    app: infra-nacos
    # 對內部服務暴露 Nacos HTTP 與 gRPC 入口。
spec:
  selector:
    app: infra-nacos
  ports:
    - name: http
      port: 8848
      targetPort: 8848
    - name: grpc
      port: 9848
      targetPort: 9848
    - name: grpc-client
      port: 9849
      targetPort: 9849
  type: ClusterIP
