spring:
  data:
    redis:
      client-type: lettuce
      # host: infra-redis.default.svc.cluster.local
      # password: ${REDIS_PASS}
      ssl: false
      timeout: 3s
      cluster:
        nodes:
          - infra-redis-0.infra-redis-headless.default.svc.cluster.local:6379
          - infra-redis-1.infra-redis-headless.default.svc.cluster.local:6379
          - infra-redis-2.infra-redis-headless.default.svc.cluster.local:6379
        max-redirects: 8
      lettuce:
        # read-from: replica-preferred
        pool:
          enabled: true
          max-active: 64
          max-idle: 32
          min-idle: 8
          max-wait: 2s
        cluster:
          refresh:
            adaptive: true
            period: 30s
  redis:
    redisson:
      file: classpath:redisson.yml

logging:
  level:
    io.lettuce.core.protocol: INFO    # Redis 操作 log
    org.redisson: INFO # Redisson 日誌
