server:
  port: 8080

spring:
  application:
    name: service-exchange-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          # Shared secret must match the auth service configuration.
          secret: ZmFrZVNlY3JldEtleUZvckRldk9ubHlVc2U=
  cloud:
    gateway:
      routes:
        # Route for the Authentication Service
        - id: auth-service-route
          uri: http://localhost:9000
          predicates:
            - Path=/api/auth/**
          filters:
            # Rewrite the path to remove the /api/auth prefix before forwarding
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}

        # Example route for a downstream service (e.g., positions service)
        # This route is protected by the security configuration.
        - id: positions-service-route
          uri: http://localhost:8081 # Assuming positions service runs on 8081
          predicates:
            - Path=/api/positions/**
          filters:
            # Rewrite the path to remove the /api prefix
            - RewritePath=/api/(?<segment>.*), /$\{segment}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
