openapi: 3.0.3
info:
  title: Exchange User Service API
  version: 1.0.0
  description: API contract for the exchange user service.
servers:
  - url: http://localhost:8080
paths:
  /api/users:
    post:
      summary: Register user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEnvelope'
    get:
      summary: List users or find by email
      operationId: listUsers
      parameters:
        - in: query
          name: email
          schema:
            type: string
          description: When provided returns the specific user
      responses:
        '200':
          description: Users returned
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/UserEnvelope'
                  - $ref: '#/components/schemas/UserListEnvelope'
  /api/users/{id}:
    get:
      summary: Get user by id
      operationId: getUserById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEnvelope'
  /api/users/{id}/status:
    patch:
      summary: Update user status
      operationId: updateUserStatus
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserStatusRequest'
      responses:
        '200':
          description: Updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEnvelope'
components:
  schemas:
    RegisterUserRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
          maxLength: 128
        externalId:
          type: string
          maxLength: 64
    UpdateUserStatusRequest:
      type: object
      required: [status]
      properties:
        status:
          $ref: '#/components/schemas/UserStatus'
    UserResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        externalId:
          type: string
        email:
          type: string
        status:
          $ref: '#/components/schemas/UserStatus'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    UserStatus:
      type: string
      enum: [ACTIVE, LOCKED, DISABLED]
    OpenApiResponse:
      type: object
      properties:
        success:
          type: boolean
        code:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
    UserEnvelope:
      allOf:
        - $ref: '#/components/schemas/OpenApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/UserResponse'
    UserListEnvelope:
      allOf:
        - $ref: '#/components/schemas/OpenApiResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/UserResponse'
