server:
  port: 0

spring:
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: off
  # 國際化
  messages:
    basename: i18n/ValidationMessages,i18n/messages

## Hibernate Validator 內部屬性
jakarta:
  validation:
    fail-fast: true   # 發現第一個違規即返回 建議開啟以早失敗

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus   # 只開放必要端點
    health:
      show-details: always                 # 開發可設 always
  metrics:
    tags:
      app: ${spring.application.name}
      env: ${APP_ENV:dev}
    web:
      server:
        request:
          autotime:
            enabled: true                  # 是否自動計時，預設 true
            percentiles: 0.5,0.9,0.95,0.99  # 計算百分位數
            percentiles-histogram: true     # 是否開啟直方圖，適合 Prometheus
        max-uri-tags: 100                  # URI 標籤上限，防止維度爆炸

logging:
  level:
    root: INFO

