apiVersion: v1
kind: Service
metadata:
  name: service-test
  labels:
    app: service-test
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  selector:
    app: service-test
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
