spring:
  web:
    locale: en-US                           #  Accept-Language head 未攜帶時的默認語系
    locale-resolver: accept_header          # 依 Accept-Language head 解析語系
  mvc:
    # 多語系默認使用: messages_en-US.properties、ValidationMessages_en-US.properties
    # @NumberFormat(style=CURRENCY) 會輸出當地貨幣符號與分位符號
    # 以樣板引擎格式化日期數字時（Thymeleaf #dates、#numbers），月份名稱、千分位、小數點等依 en-US
    # 不會設定時區與 Jackson 預設輸出，如需時區請用 spring.jackson.time-zone: Asia/Taipei。Jackson 日期預設為 ISO 格式，除非你另行設定 ObjectMapper 的 Locale/DateFormat。
    locale: en-US

  # 時間
  mvc:
    format:
      date: yyyy-MM-dd                      # 全域日期格式
      date-time: yyyy-MM-dd HH:mm:ss        # 全域日期時間格式
      time: HH:mm:ss
    cors:
      mappings:
        '/**':
          allowed-origins: ['https://app.example.com']   # 與 allow-credentials=true 不可同時使用 '*'
          allowed-methods: [GET, POST, PUT, DELETE]
          allowed-headers: [Authorization, Content-Type]
          exposed-headers: [X-Trace-Id]
          allow-credentials: true
          max-age: 3600                       # Preflight 快取秒數

open:
  vincentf13:
    mvc:
      request:
        trace-id-header: X-Trace-Id
        request-id-header: X-Request-Id
        generate-correlation-ids: true
        write-response-header: true
        filter-order: -200
      response:
        wrap-enabled: true
        ignore-controller-prefixes: []