# 預設組態說明用範本，實際專案可視需求覆寫個別屬性。
open:
  vincentf13:
    mvc:
      request:
        # 當上游未帶追蹤資訊時使用的標頭名稱。
        trace-id-header: X-Trace-Id
        request-id-header: X-Request-Id
        generate-correlation-ids: true
        write-response-header: true
        filter-order: -200
      response:
        # 啟用後自動把 REST 回應包成 ApiResponse 結構。
        wrap-enabled: true
        # 可忽略的 controller package 前綴（避免重複包裝）。
        ignore-controller-prefixes: []
