server:
  servlet:
    session:
      cookie:
        name: JSESSIONID       # cookie name ，不用 Spring Session 時才會生效
        # 僅此主機： 不要設定
        # 設 Domain=example.com 即可套用 example.com 與其所有子網域，等於 "*.example.com"
        # 不能設成公用後綴（如 .com、.co.uk）、不能設IP
        # domain: example.com
        path: /
        http-only: true        # 前端 JS 不能讀 cookie ， 開啟後前端無法以 JS 讀取，下載檔名等需改用 Content-Disposition 等回應標頭
        # 線上需改為 true
        secure: false          # 只在 HTTPS 傳送。
        # SameSite 控制 Cookie 是否在「跨站」請求中送出。Site 由「協定 + 註冊性網域」決定，子網域屬同一 site，連接埠不影響。
        # Strict：只在同站請求送出。從其他網站點連結、表單、iframe、XHR 都不送。
        # Lax：在同站送。跨站僅「頂層導覽的 GET」會送（點連結或在網址列輸入）。跨站的 POST、iframe、XHR、fetch 不送。
        # None： 所有情境都送（含跨站 XHR/iframe/POST）。必須同時 Secure=true 且走 HTTPS，否則瀏覽器丟棄。
        # 未指定時，多數瀏覽器預設 Lax。
        same-site: Lax
      timeout: 30m

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        domain: example.com
        path: /
        http-only: true
        secure: true
        same-site: None    # 跨站必須搭配 HTTPS
  # 可選：全域 session 逾時
  # servlet.session.timeout: 30m

spring:
  web:
    locale: en-US                           # Accept-Language head 未攜帶時的默認語系
    locale-resolver: accept_header          # 依 Accept-Language head 解析語系
  mvc:
                                            # 多語系默認使用: messages_en-US.properties、ValidationMessages_en-US.properties
                                            # @NumberFormat(style=CURRENCY) 會輸出當地貨幣符號與分位符號
                                            # 以樣板引擎格式化日期數字時（Thymeleaf #dates、#numbers），月份名稱、千分位、小數點等依 en-US
                                            # 不會設定時區與 Jackson 預設輸出，如需時區請用 spring.jackson.time-zone: Asia/Taipei。Jackson 日期預設為 ISO 格式，除非你另行設定 ObjectMapper 的 Locale/DateFormat。
    locale: en-US
                                            # @DateTimeFormat 的全域配置，影響表單與請求參數的解析與輸出，不影響 Jackson 的 JSON
    format:
      date: yyyy-MM-dd                      # 將 yyyy-MM-dd 作為 LocalDate，作為 LocalDateTime 的解析與輸出樣式
      date-time: yyyy-MM-dd HH:mm:ss        # 將 yyyy-MM-dd HH:mm:ss 作為 LocalDateTime 的解析與輸出樣式
      time: HH:mm:ss                        # 將 HH:mm:ss 作為 LocalTime 樣式
    cors:
      mappings:
        '/**':                                                                                         # 套用到所有 MVC 路徑。可改成特定 API 前綴（例 /api/**）縮小範圍。
          allowed-origin-patterns:                                                                     # 允許任何網域發起跨域請求，回覆 Access-Control-Allow-Origin:
            - "http://127.0.0.1:*"
            - "http://localhost:*"
            - "http://*.local"
            - "*"
          allowed-methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]                                    # 允許的 HTTP 方法
          allowed-headers: ["*"]                                                                       # 允許前端在跨域請求中攜帶的自訂請求標頭。若要全開可用 *（與 allow-credentials 不衝突）。
          exposed-headers: [Content-Disposition, X-Trace-Id, X-Request-Id]                             # 回傳 Access-Control-Expose-Headers。允許前端 JS 讀取這些回應標頭，例如取得檔名（Content-Disposition）或追蹤 ID。 "*" 在帶憑證時無效。任何網域都讀不到非 safelisted 的回應標頭，必須改成逐一列出要暴露的標頭。
          allow-credentials: true                                                                      # 回傳 Access-Control-Allow-Credentials: true。允許跨域時夾帶 Cookie 或憑證。同時必須回覆具體 Access-Control-Allow-Origin，不能是 *；前端需設 credentials: 'include'。
          max-age: 3600                                                                                # 回傳 Access-Control-Max-Age: 86400。瀏覽器可快取預檢結果 86400 秒以減少 OPTIONS。實際快取時長可能受瀏覽器上限限制。

open:
  vincentf13:
    mvc:
      request:
        trace-id-header: X-Trace-Id
        request-id-header: X-Request-Id
        generate-correlation-ids: true
        write-response-header: true
        filter-order: -200
      response:
        wrap-enabled: true
        ignore-controller-prefixes: []