server:
  forward-headers-strategy: framework   # 即使隔著反向代理，也能取得真實的使用者連線信息。例如 request.getServerName  & scheme & serverPort &contextPath
  compression:
    # 內容壓縮 請求頭需要帶： `Accept-Encoding: gzip`，響應頭自動加上  `Content-Encoding: gzip`
    enabled: true           # 開啟壓縮（預設 false）
    mime-types:             # 指定可壓縮的內容類型
      - application/json
      - application/xml
      - text/html
      - text/plain
      - text/css
      - application/javascript
    min-response-size: 1024 # 壓縮門檻，超過才壓縮，單位 bytes
  servlet:
    session:
      cookie:
        name: JSESSIONID       # cookie name ，不用 Spring Session 時才會生效
        # 僅此主機： 不要設定
        # 設 Domain=example.com 即可套用 example.com 與其所有子網域，等於 "*.example.com"
        # 不能設成公用後綴（如 .com、.co.uk）、不能設IP
        # domain: example.com
        path: /
        http-only: true        # 前端 JS 不能讀 cookie ， 開啟後前端無法以 JS 讀取，下載檔名等需改用 Content-Disposition 等回應標頭
        # 線上需改為 true
        secure: false          # 只在 HTTPS 傳送。
        # SameSite 控制 Cookie 是否在「跨站」請求中送出。Site 由「協定 + 註冊性網域」決定，子網域屬同一 site，連接埠不影響。
        # Strict：只在同站請求送出。從其他網站點連結、表單、iframe、XHR 都不送。
        # Lax：在同站送。跨站僅「頂層導覽的 GET」會送（點連結或在網址列輸入）。跨站的 POST、iframe、XHR、fetch 不送。
        # None： 所有情境都送（含跨站 XHR/iframe/POST）。必須同時 Secure=true 且走 HTTPS，否則瀏覽器丟棄。
        # 未指定時，多數瀏覽器預設 Lax。
        same-site: Lax
      timeout: 30m


spring:
  web:
    locale: en-US                           # Accept-Language head 未攜帶時的默認語系
    locale-resolver: accept_header          # 依 Accept-Language head 解析語系
  mvc:
                                            # 多語系默認使用: messages_en-US.properties、ValidationMessages_en-US.properties
                                            # @NumberFormat(style=CURRENCY) 會輸出當地貨幣符號與分位符號
                                            # 以樣板引擎格式化日期數字時（Thymeleaf #dates、#numbers），月份名稱、千分位、小數點等依 en-US
                                            # 不會設定時區與 Jackson 預設輸出，如需時區請用 spring.jackson.time-zone: Asia/Taipei。Jackson 日期預設為 ISO 格式，除非你另行設定 ObjectMapper 的 Locale/DateFormat。
    locale: en-US
                                            # @DateTimeFormat 的全域配置，影響表單與請求參數的解析與輸出，不影響 Jackson 的 JSON
    format:
      date: yyyy-MM-dd                      # 將 yyyy-MM-dd 作為 LocalDate，作為 LocalDateTime 的解析與輸出樣式
      date-time: yyyy-MM-dd HH:mm:ss        # 將 yyyy-MM-dd HH:mm:ss 作為 LocalDateTime 的解析與輸出樣式
      time: HH:mm:ss                        # 將 HH:mm:ss 作為 LocalTime 樣式
    hidden-method:
      filter:
        enabled: true

open:
  vincentf13:
    mvc:
      request:
        trace-id-header: X-Trace-Id
        request-id-header: X-Request-Id
        generate-correlation-ids: true
        write-response-header: true
        filter-order: -200
      response:
        wrap-enabled: true
        ignore-controller-prefixes: []