spring:
  # 多語系
  messages:
    basename: i18n/messages                 # 多語系檔根名，省略 classpath: 前綴
    fallback-to-system-locale: false        # 不回退到系統語系
  web:
    locale: en-US                           # 預設語系
    locale-resolver: accept_header          # 依 Accept-Language 解析
  # 時間
  mvc:
    format:
      date: yyyy-MM-dd                      # 全域日期格式
      date-time: yyyy-MM-dd HH:mm:ss        # 全域日期時間格式
      time: HH:mm:ss
    cors:
      mappings:
        '/**':
          allowed-origins: ['https://app.example.com']   # 與 allow-credentials=true 不可同時使用 '*'
          allowed-methods: [GET, POST, PUT, DELETE]
          allowed-headers: [Authorization, Content-Type]
          exposed-headers: [X-Trace-Id]
          allow-credentials: true
          max-age: 3600                       # Preflight 快取秒數
jakarta:
  validation:
    fail-fast: true                                    # 啟用 fail-fast 驗證策略
open:
  vincentf13:
    mvc:
      request:
        trace-id-header: X-Trace-Id
        request-id-header: X-Request-Id
        generate-correlation-ids: true
        write-response-header: true
        filter-order: -200
      response:
        wrap-enabled: true
        ignore-controller-prefixes: []