apiVersion: v1
kind: PersistentVolume
metadata:
  name: infra-mysql-pv-0
  labels:
    app: infra-mysql
    role: primary
    # 專供 StatefulSet 第 0 顆 Pod 使用。
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # 保留資料，避免刪除 PVC 時誤刪檔案。
  storageClassName: infra-mysql-local
  hostPath:
    path: /var/lib/k8s/infra-mysql-0
    type: DirectoryOrCreate  # 若目錄不存在自動建立。

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: infra-mysql-pv-1
  labels:
    app: infra-mysql
    role: replica
    # 專供 StatefulSet 第 1 顆 Pod 使用。
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # 保留資料，避免刪除 PVC 時誤刪檔案。
  storageClassName: infra-mysql-local
  hostPath:
    path: /var/lib/k8s/infra-mysql-1
    type: DirectoryOrCreate  # 若目錄不存在自動建立。
