apiVersion: v1
kind: PersistentVolume
metadata:
  name: infra-mysql-pv-0
  labels:
    app: infra-mysql
    role: primary
    # 使用本地 hostPath 提供第 0 個 StatefulSet Pod 的儲存。
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # 保留資料，避免刪除 PVC 時誤刪檔案。
  storageClassName: infra-mysql-local
  hostPath:
    path: /var/lib/k8s/infra-mysql-0
    type: DirectoryOrCreate  # 若目錄不存在自動建立。
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: infra-mysql-pv-1
  labels:
    app: infra-mysql
    role: replica
    # 提供第 1 個 StatefulSet Pod 的儲存空間。
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: infra-mysql-local
  hostPath:
    path: /var/lib/k8s/infra-mysql-1
    type: DirectoryOrCreate
