apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-mysql-pvc
  labels:
    app: infra-mysql
    # 與 StatefulSet 綁定的 PVC，要求前面建立的 PV。
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: infra-mysql-local
  volumeName: infra-mysql-pv  # 指定綁定同名 PV，避免誤綁到其他 volume。
