apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-infra-mysql-0
  labels:
    app: infra-mysql
    role: primary
    # 與 volumeClaimTemplates 產生的 PVC 命名一致，用於預先綁定第 0 顆 PV。
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: infra-mysql-local
  volumeName: infra-mysql-pv-0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-infra-mysql-1
  labels:
    app: infra-mysql
    role: replica
    # 預先綁定第 1 顆 PV，確保第二個 Pod 也能掛載資料。
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: infra-mysql-local
  volumeName: infra-mysql-pv-1
