apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-mysql-mysql-data-0
  labels:
    app: infra-mysql
    role: primary
    # 對應 StatefulSet 第 0 個 Pod，自動被 volumeClaimTemplates 掛載。
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: infra-mysql-local
  volumeName: infra-mysql-pv-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-mysql-mysql-data-1
  labels:
    app: infra-mysql
    role: replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: infra-mysql-local
  volumeName: infra-mysql-pv-1
