apiVersion: v1
kind: Secret
metadata:
  name: infra-mysql-secret
  labels:
    app: infra-mysql
    # 儲存 root 與應用帳密，StatefulSet 以 envFrom 方式載入。
type: Opaque
stringData:
  # 請在佈署前改為實際密碼，或改用外部 secret 管理機制。
  MYSQL_ROOT_PASSWORD: root
  MYSQL_ROOT_HOST: '%'
  MYSQL_DATABASE: app
  MYSQL_USER: app_user
  MYSQL_PASSWORD: app_user
