apiVersion: v1
kind: Service
metadata:
  name: infra-mysql
  labels:
    app: infra-mysql
    # ClusterIP 服務對外暴露 MySQL，並提供 StatefulSet DNS 解析。
spec:
  selector:
    app: infra-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
