apiVersion: v1
kind: Service
metadata:
  name: infra-mysql
  labels:
    app: infra-mysql
spec:
  clusterIP: None  # 設為 headless，讓 StatefulSet Pod 取得穩定 DNS： <Pod名稱>.<Service名稱>.<Namespace>.svc.cluster.local
  selector:
    app: infra-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
