spring:
  cloud:
    openfeign:
      enabled: true
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 5000
            loggerLevel: FULL
      compression:
        request:
          enabled: true
          mime-types:
            - text/xml
            - application/json
          min-request-size: 2048
        response:
          enabled: true

logging:
  level:
    feign.http: DEBUG

security:
  api-key:
    client:
      enabled: true
      value: default-1
