openapi: 3.0.3
info:
  title: Exchange Auth Service API
  version: 1.0.0
  description: API contract for the exchange auth service.
servers:
  - url: http://localhost:8080
paths:
  /api/auth/credentials:
    post:
      summary: Create credential
      operationId: createCredential
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCredentialCreateRequest'
      responses:
        '200':
          description: Credential created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthCredentialEnvelope'
    get:
      summary: Find credential by user id and type
      operationId: findCredential
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: type
          required: true
          schema:
            $ref: '#/components/schemas/AuthCredentialType'
      responses:
        '200':
          description: Credential found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthCredentialEnvelope'
components:
  schemas:
    AuthCredentialCreateRequest:
      type: object
      required: [userId, credentialType, secret, status]
      properties:
        userId:
          type: integer
          format: int64
        credentialType:
          $ref: '#/components/schemas/AuthCredentialType'
        secret:
          type: string
          maxLength: 512
        status:
          type: string
          maxLength: 32
    AuthCredentialResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        credentialType:
          $ref: '#/components/schemas/AuthCredentialType'
        status:
          type: string
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
    AuthCredentialType:
      type: string
      enum: [PASSWORD, API_KEY]
    OpenApiResponse:
      type: object
      properties:
        code:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time
        meta:
          type: object
          additionalProperties: true
    AuthCredentialEnvelope:
      allOf:
        - $ref: '#/components/schemas/OpenApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/AuthCredentialResponse'
