openapi: 3.0.3
info:
  title: Exchange Auth Service API
  version: 1.0.0
  description: API contract for the exchange auth service.
servers:
  - url: http://localhost:8080
paths:
  /api/auth/credentials:
    post:
      summary: Create credential
      operationId: createCredential
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCredentialCreateRequest'
      responses:
        '200':
          description: Credential created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthCredentialEnvelope'
  /api/auth/credentials/prepare:
    post:
      summary: Prepare credential secret
      operationId: prepareCredential
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthCredentialPrepareRequest'
      responses:
        '200':
          description: Prepared credential secret
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthCredentialPrepareEnvelope'
components:
  schemas:
    AuthCredentialCreateRequest:
      type: object
      required: [userId, credentialType, secretHash, salt, status]
      properties:
        userId:
          type: integer
          format: int64
        credentialType:
          $ref: '#/components/schemas/AuthCredentialType'
        secretHash:
          type: string
          maxLength: 512
        salt:
          type: string
          maxLength: 128
        status:
          type: string
          maxLength: 32
    AuthCredentialPrepareRequest:
      type: object
      required: [credentialType, secret]
      properties:
        credentialType:
          $ref: '#/components/schemas/AuthCredentialType'
        secret:
          type: string
          maxLength: 512
    AuthCredentialPrepareResponse:
      type: object
      properties:
        secretHash:
          type: string
        salt:
          type: string
    AuthCredentialResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        credentialType:
          $ref: '#/components/schemas/AuthCredentialType'
        status:
          type: string
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
    AuthCredentialType:
      type: string
      enum: [PASSWORD, API_KEY]
    OpenApiResponse:
      type: object
      properties:
        code:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time
        meta:
          type: object
          additionalProperties: true
    AuthCredentialEnvelope:
      allOf:
        - $ref: '#/components/schemas/OpenApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/AuthCredentialResponse'
    AuthCredentialPrepareEnvelope:
      allOf:
        - $ref: '#/components/schemas/OpenApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/AuthCredentialPrepareResponse'
