apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
  labels:
    app: redpanda-console
spec:
  selector:
    app: redpanda-console
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
