logging:
  level:
    root: INFO
    open.vincentf13: WARN

server:
  port: 8082

websocket:
  port: 8080

spring:
  application:
    name: spot-gateway

aeron:
  dir: C:/iProject/open.vincentf13/data/spot-exchange/aeron
  driver:
    enabled: false

state:
  base-dir: C:/iProject/open.vincentf13/data/spot-exchange/
