logging:
  level:
    root: INFO
    open.vincentf13: WARN
    open.vincentf13.service.spot.infra.thread: INFO
    open.vincentf13.service.spot.ws.aeron: INFO
    open.vincentf13.service.spot.ws.ws: INFO
    net.openhft.chronicle: WARN

server:
  port: 8082

websocket:
  port: 8080

netty:
  worker:
    count: 3

spring:
  application:
    name: spot-gateway

aeron:
  dir: C:/iProject/open.vincentf13/data/spot-exchange/aeron

state:
  base-dir: C:/iProject/open.vincentf13/data/spot-exchange/
