spring:
  data:
    redis:
      client-type: lettuce
      # host: localhost
      # password: ${REDIS_PASS}
      ssl: false
      timeout: 3s
      cluster:
        nodes:
          - localhost:6379
          - localhost:6380
          - localhost:6381
        max-redirects: 8
      lettuce:
        # read-from: replica-preferred
        pool:
          enabled: true
          max-active: 64
          max-idle: 32
          min-idle: 8
          max-wait: 2s
        cluster:
          refresh:
            adaptive: true
            period: 30s
  redis:
    redisson:
      file: classpath:redisson.yml

logging:
  level:
    io.lettuce.core.protocol: INFO    # Regis 操作 log
