server:
  port: 12345
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000          # 連線超時 5s
        response-timeout: 10s          # 回應超時 10s
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: user-api
#          uri: lb://user-service
#          predicates:
#            - Path=/api/users/**


open:
  vincentf13:
    security:
      gateway:
        permit-paths:
          - /actuator/**


logging:
  level:
    open.vincentf13.sdk.spring.cloud.gateway.jwt: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.http.server.reactive: DEBUG
#    org.springframework.web.reactive: DEBUG
#    reactor.netty: DEBUG



